services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=m5tryapp
      - DOCKER_INFLUXDB_INIT_BUCKET=m5tryapp
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=m5tryapp
    volumes:
      - ./dashboard.json:/dashboard.json
    command: /entrypoint.sh && bash init.sh
